<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use Rdsco\AttReport\Auth;use Rdsco\AttReport\Helpers;use Rdsco\AttReport\JobStore;
$csrf=Helpers::csrfToken();$hasUsers=Auth::hasUsers();$user=Auth::user();$meta=null;
if($user&&!empty($_SESSION['job_id'])){try{$meta=JobStore::meta((string)$_SESSION['job_id']);}catch(Throwable){unset($_SESSION['job_id']);}}
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><meta name="robots" content="noindex,nofollow,noarchive"><title>سامانه گزارش تردد RDSCO</title><link rel="stylesheet" href="assets/css/app.css?v=1"></head><body><div id="toast" class="toast hidden"></div>
<?php if(!$hasUsers): ?>
<main class="auth-shell"><section class="auth-card"><div class="brand-mark">R</div><p class="eyebrow">راه‌اندازی اولیه</p><h1>سامانه گزارش تردد</h1><p class="muted">اولین اپراتور را ایجاد کنید. بعد از آن ثبت‌نام عمومی بسته می‌شود.</p><form class="ajax-form stack" data-action="setup"><label>شماره موبایل<input name="mobile" inputmode="numeric" placeholder="09123456789" required></label><label>رمز عبور<input type="password" name="password" minlength="10" required></label><label>تکرار رمز<input type="password" name="password_confirmation" minlength="10" required></label><button class="btn primary">ایجاد حساب اپراتور</button></form></section></main>
<?php elseif(!$user): ?>
<main class="auth-shell"><section class="auth-card wide"><div class="brand-row"><div class="brand-mark">R</div><div><p class="eyebrow">RDSCO</p><h1>ورود به پنل گزارش تردد</h1></div></div><div class="tabs"><button type="button" class="tab active" data-tab="password">رمز عبور</button><button type="button" class="tab" data-tab="otp">رمز یکبار مصرف</button></div><div id="tab-password" class="tab-panel"><form class="ajax-form stack" data-action="login"><label>شماره موبایل<input name="mobile" inputmode="numeric" required></label><label>رمز عبور<input type="password" name="password" required></label><button class="btn primary">ورود امن</button></form></div><div id="tab-otp" class="tab-panel hidden"><form id="otp-request-form" class="ajax-form stack" data-action="request_otp"><label>شماره موبایل<input name="mobile" inputmode="numeric" required></label><button class="btn secondary">ارسال رمز</button></form><form id="otp-verify-form" class="ajax-form stack" data-action="verify_otp"><label>کد ۶ رقمی<input name="otp" inputmode="numeric" maxlength="6" required></label><input type="hidden" name="mobile"><button class="btn primary">تأیید و ورود</button></form></div></section></main>
<?php else: ?>
<div class="layout"><aside class="sidebar"><div><div class="brand-row compact"><div class="brand-mark">R</div><div><strong>RDSCO</strong><span>Attendance Report</span></div></div><nav><a href="#upload">فایل ساعت‌زنی</a><a href="#reports">گزارش و خروجی</a><a href="#logs">لاگ فعالیت‌ها</a></nav></div><div class="user-box"><span>اپراتور</span><strong><?=htmlspecialchars((string)$user['mobile'],ENT_QUOTES,'UTF-8')?></strong><button id="logout-btn" class="link-btn">خروج</button></div></aside><main class="content">
<header class="page-head"><div><p class="eyebrow">داشبورد</p><h1>گزارش تردد پرسنل</h1><p class="muted">فایل خروجی دستگاه را بارگذاری کنید، بازه شمسی را انتخاب کنید و خروجی بگیرید.</p></div><span class="status-chip">ورود امن</span></header>
<section id="upload" class="panel"><div class="section-head"><div><h2>۱. بارگذاری فایل دستگاه</h2><p>DAT، TXT و CSV</p></div><span class="step">01</span></div><form id="upload-form" class="upload-box" enctype="multipart/form-data"><input id="attendance-file" type="file" name="attendance_file" accept=".dat,.txt,.csv" required><label for="attendance-file"><span class="upload-icon">⇧</span><span><strong>فایل را انتخاب کنید</strong><small>پردازش بدون نگهداری فایل اصلی</small></span></label><button class="btn primary">پردازش فایل</button></form><div id="file-meta" class="meta-grid <?=$meta?'':'hidden'?>"><div><span>رکورد معتبر</span><strong data-meta="records"><?=$meta['records']??'—'?></strong></div><div><span>پرسنل</span><strong data-meta="employee_count"><?=$meta['employee_count']??'—'?></strong></div><div><span>شروع شمسی</span><strong data-meta="min_jalali"><?=$meta['min_jalali']??'—'?></strong></div><div><span>پایان شمسی</span><strong data-meta="max_jalali"><?=$meta['max_jalali']??'—'?></strong></div></div></section>
<section id="reports" class="panel"><div class="section-head"><div><h2>۲. بازه گزارش</h2><p>فیلتر با تاریخ شمسی؛ خروجی شامل شمسی و میلادی است.</p></div><span class="step">02</span></div><form id="filter-form" class="filter-row"><label>از تاریخ شمسی<input name="from_jalali" value="<?=htmlspecialchars((string)($meta['min_jalali']??''),ENT_QUOTES,'UTF-8')?>" placeholder="1405/01/01" required></label><label>تا تاریخ شمسی<input name="to_jalali" value="<?=htmlspecialchars((string)($meta['max_jalali']??''),ENT_QUOTES,'UTF-8')?>" placeholder="1405/12/29" required></label><button class="btn secondary">اعمال فیلتر</button></form><div id="filter-summary" class="summary-strip hidden"><div><span>رکورد</span><strong data-summary="record_count">0</strong></div><div><span>پرسنل</span><strong data-summary="employee_count">0</strong></div><div><span>روز/پرسنل</span><strong data-summary="day_count">0</strong></div><div><span>بازه میلادی</span><strong data-summary="gregorian_range">—</strong></div></div><div class="export-actions"><button class="btn excel" data-export="export_xlsx">دریافت Excel</button><button class="btn pdf" data-export="export_pdf">دریافت PDF افقی</button></div><div class="notice"><strong>منطق ورود/خروج:</strong> اولین ثبت هر روز ورود و آخرین ثبت خروج؛ تک‌ثبت به‌صورت نامشخص علامت‌گذاری می‌شود.</div></section>
<section id="logs" class="panel"><div class="section-head"><div><h2>۳. لاگ فعالیت اپراتور</h2><p>ورود، خروج، آپلود، فیلتر و خروجی‌ها ثبت می‌شوند.</p></div><button id="refresh-logs" class="link-btn">به‌روزرسانی</button></div><div class="table-wrap"><table><thead><tr><th>زمان</th><th>عملیات</th><th>کاربر</th><th>IP</th></tr></thead><tbody id="logs-body"><tr><td colspan="4" class="muted">برای مشاهده لاگ‌ها به‌روزرسانی را بزنید.</td></tr></tbody></table></div></section>
</main></div>
<?php endif; ?><script src="assets/js/app.js?v=1" defer></script></body></html>
