<?php
declare(strict_types=1);
namespace Rdsco\AttReport;
use RuntimeException;
final class PdfRenderer
{
    public static function build(string $path,array $report,string $fromJalali,string $toJalali): void
    {
        $browser=trim((string)Env::get('PDF_BROWSER_PATH',''));if($browser===''||!is_file($browser)||!is_executable($browser))throw new RuntimeException('مسیر Chromium/Chrome محلی برای تولید PDF تنظیم نشده است.');
        if(!function_exists('proc_open'))throw new RuntimeException('تابع proc_open در PHP غیرفعال است و تولید PDF سمت سرور ممکن نیست.');
        $htmlPath=dirname($path).'/report-'.bin2hex(random_bytes(6)).'.html';$profileDir=dirname($path).'/chrome-'.bin2hex(random_bytes(6));@mkdir($profileDir,0700,true);file_put_contents($htmlPath,self::html($report,$fromJalali,$toJalali));@chmod($htmlPath,0600);
        $command=[$browser,'--headless=new','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-component-update','--disable-default-apps','--disable-extensions','--disable-sync','--metrics-recording-only','--no-first-run','--no-pdf-header-footer','--user-data-dir='.$profileDir,'--print-to-pdf='.$path];if(Env::bool('PDF_NO_SANDBOX',false))$command[]='--no-sandbox';$command[]='file://'.$htmlPath;
        $pipes=[];$process=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname($htmlPath));if(!is_resource($process)){@unlink($htmlPath);self::removeDir($profileDir);throw new RuntimeException('اجرای مرورگر محلی برای PDF ممکن نیست.');}
        foreach($pipes as $pipe)stream_set_blocking($pipe,false);$timeout=max(10,Env::int('PDF_TIMEOUT_SECONDS',60));$started=microtime(true);$timedOut=false;
        while(true){$status=proc_get_status($process);stream_get_contents($pipes[1]);if(!$status['running'])break;if((microtime(true)-$started)>$timeout){$timedOut=true;proc_terminate($process,9);break;}usleep(100000);}
        foreach($pipes as $pipe)@fclose($pipe);proc_close($process);@unlink($htmlPath);self::removeDir($profileDir);
        if($timedOut||!is_file($path)||filesize($path)<500){@unlink($path);$hint=$timedOut?' (مهلت اجرای مرورگر تمام شد)':'';throw new RuntimeException('Chromium نتوانست PDF را تولید کند'.$hint.'. مسیر PDF_BROWSER_PATH، Sandbox و مجوز proc_open را بررسی کنید.');}@chmod($path,0600);
    }
    private static function removeDir(string $dir): void { if(!is_dir($dir))return;foreach(scandir($dir)?:[] as $item){if($item==='.'||$item==='..')continue;$path=$dir.'/'.$item;if(is_dir($path)&&!is_link($path))self::removeDir($path);else @unlink($path);}@rmdir($dir); }
    private static function html(array $report,string $fromJalali,string $toJalali): string
    {
        $fontFile=PUBLIC_PATH.'/assets/fonts/Vazirmatn-Regular.woff2';$fontCss=is_file($fontFile)?"@font-face{font-family:'Vazirmatn';src:url('file://".str_replace("'",'%27',$fontFile)."') format('woff2');font-weight:100 900;font-style:normal;}":'';
        $byEmployee=[];foreach($report['daily'] as $row)$byEmployee['e:'.$row['employee_id']][]=$row;ksort($byEmployee,SORT_NATURAL);
        $style=$fontCss."@page{size:A4 landscape;margin:10mm 9mm 11mm}*{box-sizing:border-box}body{margin:0;direction:rtl;font-family:'Vazirmatn',Tahoma,Arial,sans-serif;color:#0f172a;background:#fff;font-size:10px}.employee{break-before:page}.employee:first-child{break-before:auto}.report-table{width:100%;border-collapse:collapse;table-layout:fixed}.report-table thead{display:table-header-group}.report-table tr{break-inside:avoid}.hero th{padding:0 0 8px;border:0}.hero-card{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border:1px solid #dbe4ea;border-radius:14px;background:#f8fafc}.title{font-size:16px;font-weight:800;margin:0 0 3px}.sub{font-size:9px;color:#64748b}.badge{display:inline-flex;padding:4px 9px;border-radius:999px;background:#ccfbf1;color:#115e59;font-weight:700;margin-right:6px}.head th{background:#0f766e;color:white;padding:8px 6px;font-weight:700;text-align:center}.report-table td{padding:7px 5px;border-bottom:1px solid #e2e8f0;text-align:center;vertical-align:middle;line-height:1.6}.report-table tbody tr:nth-child(even){background:#f8fafc}.single{background:#fff7ed!important}.single td:last-child{color:#c2410c;font-weight:700}.middle{font-size:8.8px;direction:ltr}.footnote{margin-top:8px;padding:8px 10px;border:1px solid #fde68a;background:#fffbeb;border-radius:10px;color:#92400e;font-size:9px;break-inside:avoid}.ltr{direction:ltr;unicode-bidi:embed}";
        $html='<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><style>'.$style.'</style></head><body>';
        foreach($byEmployee as $employeeKey=>$rows){$employee=substr((string)$employeeKey,2);$recordCount=array_sum(array_column($rows,'count'));$html.='<section class="employee"><table class="report-table"><thead><tr class="hero"><th colspan="9"><div class="hero-card"><div><div class="title">گزارش ورود و خروج پرسنل</div><div class="sub">بازه شمسی '.self::e($fromJalali).' تا '.self::e($toJalali).' · تاریخ میلادی نیز در هر ردیف درج شده است.</div></div><div><span class="badge">کد پرسنلی: '.self::e($employee).'</span><span class="badge">'.count($rows).' روز · '.$recordCount.' ثبت</span></div></div></th></tr><tr class="head"><th>ردیف</th><th>تاریخ شمسی</th><th>تاریخ میلادی</th><th>ورود</th><th>خروج</th><th>ترددهای میانی</th><th>تعداد</th><th>فاصله</th><th>وضعیت</th></tr></thead><tbody>';
            foreach($rows as $i=>$row){$single=$row['count']===1;$html.='<tr class="'.($single?'single':'').'"><td>'.($i+1).'</td><td class="ltr">'.self::e($row['jalali_date']).'</td><td class="ltr">'.self::e($row['gregorian_date']).'</td><td class="ltr">'.self::e($row['first_entry']).'</td><td class="ltr">'.self::e($row['last_exit']??'—').'</td><td class="middle">'.self::e($row['middle']?implode(' · ',$row['middle']):'—').'</td><td>'.self::e($row['count']).'</td><td class="ltr">'.self::e($row['span']??'—').'</td><td>'.self::e($row['status']).'</td></tr>';}$html.='</tbody></table><div class="footnote">نکته: چون فایل دستگاه نوع ورود/خروج قابل اتکایی ارائه نمی‌کند، اولین ثبت هر روز «ورود» و آخرین ثبت «خروج» در نظر گرفته می‌شود. روزهای دارای فقط یک ثبت با وضعیت «تک‌ثبت / نامشخص» مشخص شده‌اند.</div></section>';}
        return $html.'</body></html>';
    }
    private static function e(string|int|float $value): string { return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
}
